name: 'crypto_pipeline'
version: '1.0.0'
config-version: 2

profile: 'crypto_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
packages-install-path: "dbt_packages_local"

clean-targets:
  - "target"
  - "dbt_packages_local"

models:
  crypto_pipeline:
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: table
