FROM python:3.10-slim-bookworm

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless procps \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    kafka-python-ng==2.2.2 \
    psycopg2-binary==2.9.9 \
    pyspark==3.5.0 \
    python-dotenv==1.0.0

COPY processing/ ./processing/
COPY storage/ ./storage/

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PYTHONPATH=/app

CMD ["python", "processing/spark_streaming.py"]
